---
services:
  default:
    container_name: redis-stack
    hostname: redis-stack
    image: redis/redis-stack:latest
    environment:
      REDIS_ARGS: "--requirepass redis"
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
      - 8001:8001

volumes:
  redis-data:
