site:
  title: Neoland
  start_page: neoland:ROOT:index.adoc
content:
  sources:
    - url: .
      start_path: docs
      branches: HEAD
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./docs/supplemental-ui

asciidoc:
  extensions:
    - asciidoctor-kroki