users:
  - default
  - name: ai
    gecos: AI
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDTypDcnR9poPyepE7yWaA9CjRnUEyKDfxLOmcFfLf28hTOR1/ipd9tEKwnyQLp4Ap5bTYOSFtkp8ou962iwMKwSKxBNeY/3HoGppIejw7XAN/wedDv4VlUxGokyDdjnKspoGzMZoH0qIx2FAZDhHTbWJASkX979nA5stYR3w0d8GeZLMH2fJDQUPhdJe6nhY+zGuTM7qJDzks4nN7Yt3qV47y0L+E59oR4RTGkKGvnvV2EZMzLRWopDGrt2aT50V4kMxHbIT9nFG62sAFfC8+QSwmv0/sKVzg8doEDe75Q3NuK8sSuc1hK3kRp/KkGDj/yZmBIn/Yno74Fu4GujJ1/ zhenyuanlau@outlook.com

package_update: true
package_upgrade: true

packages:
  - git