model_list:
  - model_name: llama3
    litellm_params:
      model: ollama/llama3:latest
      api_base: http://host.docker.internal:11434
  - model_name: dolphincoder
    litellm_params:
      model: ollama/dolphincoder:latest
      api_base: http://host.docker.internal:11434