---
services:
  default:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos-standalone
    platform: "linux/amd64"
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - NACOS_AUTH_IDENTITY_KEY=serverIdentity
      - NACOS_AUTH_IDENTITY_VALUE=security
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
    volumes:
      - nacos-logs:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"

volumes:
  nacos-logs: