---
- name: IaC for Orbstack
  hosts: localhost
  gather_facts: false
  vars:
    components:
      - redis
      - postgres
      - metabase
      - rabbitmq
      - kafka
      - clickhouse
      - nacos
      - localstack
      - litellm
      - livebook
  tasks:
    - name: Tear down land
      community.docker.docker_compose_v2:
        project_src: ../dockers/{{ item }}
        state: absent
        remove_orphans: true
        remove_volumes: true
      with_items: "{{ components }}"
      tags:
        - land
    - name: Create and start land
      community.docker.docker_compose_v2:
        project_src: ../dockers/{{ item }}
      with_items: "{{ components }}"
      tags:
        - land
    - name: Include components
      ansible.builtin.include_tasks:
        file: tasks/component.yml
        apply:
          tags:
            - "{{ item }}"
      with_items: "{{ components }}"
      tags:
        - component
